version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - 2181:2181
    kafka:
        image: wurstmeister/kafka:1.1.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "inbound:1:1,outbound:1:1"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        ports:
        - 9092:9092
    redis:
        image: redis
        ports:
        - "6379:6379"
        restart: always
